package com.example.SmartApparel.Operations.dto;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@AllArgsConstructor //generate a constructor with all fields as parameters
@NoArgsConstructor//generate a no-arguments constructor
@Data //generate getters, setters, equals, hashCode, and toString methods
public class InventoryDTO {
    @Id//mark this field as the primary key
    //primary key value will be automatically generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int itemID;
    private String itemCategory;
    private String itemName;
    private float stockQty;
    private String unit;
    private float purchasePrice;
    private LocalDate purchaseDate;
}
