package com.example.SmartApparel.Operations.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Entity//class mapped to database
@AllArgsConstructor //generate a constructor with all fields as parameters
@NoArgsConstructor//generate a no-arguments constructor
@Data//generate getters, setters, equals, hashCode, and toString methods
@Table(name = "Inventory")

public class Inventory {
    @Id// specify PK
    //primary key value will be automatically generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int itemID;
    private String itemCategory;
    private String itemName;
    private float stockQty;
    private String unit;
    private float purchasePrice;
    private LocalDate purchaseDate;
}
